package com.junkbyte.console
{
	public class ConsoleLevel
	{
		public static const CONSOLE_STATUS:int = -1; // lines generated by console
		public static const CONSOLE_EVENT:int = -2; // lines generated by console
		
		public static const LOG:uint = 1;
		public static const INFO:uint = 3;
		public static const DEBUG:uint = 6;
		public static const WARN:uint = 8;
		public static const ERROR:uint = 9;
		public static const FATAL:uint = 10;
	}
}